name: Synchronize Transactions
on:
  workflow_dispatch:
    inputs:
      dry:
        type: boolean
        default: true
  schedule:
    - cron: '0 0 * * *'
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - run: ruby ./lib/ynab/splitter.rb -v --key "${{ secrets.YNAB_API_KEY }}" ${{ inputs.dry && '--dry'}}
